//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub username: String,
    pub hashed_password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::token_invalidation::Entity")]
    TokenInvalidation,
}

impl Related<super::token_invalidation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TokenInvalidation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
